version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
      - static
      - cadvisor
    ports:
      - "443:443"
    volumes:
      - /home/$USERNAME_SESSION/data/wp_web:/var/www/html
      - static:/usr/share/nginx/html
    env_file:
      - .env
    networks:
      inception:
    restart: always
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - /home/$USERNAME_SESSION/data/wp_web:/var/www/html
    env_file:
      - .env
    networks:
      inception:
    restart: always
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    environment:
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
    volumes:
      - /home/$USERNAME_SESSION/data/maria_database:/var/lib/mysql
    env_file:
      - .env
    networks:
      inception:
    restart: always
  redis:
    build: requirements/bonus/redis/.
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/$USERNAME_SESSION/data/redis_data:/data
    networks:
      inception:
    restart: always 
  ftp:
    build: requirements/bonus/ftp/.
    container_name: ftp
    ports:
      - "20:20"
      - "21:21"
    volumes:
      - /home/$USERNAME_SESSION/data/wp_web:/var/www/html
    env_file:
      - .env
    networks:
      inception:
    restart: always
  adminer:
    build: requirements/bonus/adminer/.
    container_name: adminer
    ports:
      - "9090:9090"
    depends_on:
      - mariadb
    networks:
      inception:
    restart: always
  static:
    container_name: static
    image: static:42
    init: true
    build:
      context: ./requirements/bonus/static_website
      dockerfile: Dockerfile
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - static:/usr/src/app
    restart: always
  cadvisor:
    build: ./requirements/bonus/cadvisor/.
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080" #cadvisor has to be on 8080
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - inception

volumes:
  static:
    name: static
networks:
  inception:
