version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - /home/$USERNAME_SESSION/data/wp_web:/var/www/html
      - /var/log/nginx:/var/log/nginx
    env_file:
      - .env
    networks:
      inception:
    restart: on-failure
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - /home/$USERNAME_SESSION/data/wp_web:/var/www/html
    env_file:
      - .env
    networks:
      inception:
    restart: on-failure
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    environment:
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
    volumes:
      - /home/$USERNAME_SESSION/data/maria_database:/var/lib/mysql
    env_file:
      - .env
    networks:
      inception:
    restart: on-failure
  redis:
    build: requirements/bonus/redis/.
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/$USERNAME_SESSION/data/redis_data:/data
    networks:
      inception:
    restart: on-failure
  ftp:
    build: requirements/bonus/ftp/.
    container_name: ftp
    ports:
      - "20:20"
      - "21:21"
    volumes:
      - /home/$USERNAME_SESSION/data/wp_web:/var/www/html
    env_file:
      - .env
    networks:
      inception:
    restart: on-failure
  adminer:
    build: requirements/bonus/adminer/.
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      inception:
    restart: on-failure
  static_website:
    build: requirements/bonus/static_website/.
    container_name: static_website
    ports:
      - "8081:80"
    volumes:
      - ./requirements/bonus/static_website/html/.:/usr/share/nginx/html/.:ro
    networks:
      inception:
    restart: on-failure
  fail2ban:
    build: requirements/bonus/fail2ban/.
    container_name: fail2ban
    cap_add:
      - NET_ADMIN  # Permet de modifier iptables
    volumes:
      - /var/log/nginx:/var/log/nginx:ro
      - ./requirements/bonus/fail2ban/jail.local:/etc/fail2ban/jail.local
    networks:
      inception:
    restart: on-failure

networks:
  inception:
