version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - /home/simon/data/wp_web:/var/www/html
    networks:
      inception:
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - /home/simon/data/wp_web:/var/www/html
    networks:
      inception:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - /home/simon/data/maria_database:/var/lib/mysql
    networks:
      inception:

networks:
  inception:
