version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - /home/simon/data/wp_web:/var/www/html
    networks:
      inception:
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - /home/simon/data/wp_web:/var/www/html
    networks:
      inception:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - /home/simon/data/maria_database:/var/lib/mysql
    networks:
      inception:
  redis:
    build: requirements/bonus/redis/.
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/simon/data/redis_data:/data
    networks:
      inception:
  ftp:
    build: requirements/bonus/ftp/.
    container_name: ftp
    ports:
      - "20:20"
      - "21:21"
    volumes:
      - /home/simon/data/ftp:
    networks:
      inception:

networks:
  inception:
