-- CREATE USER 'wpuser'@'%' IDENTIFIED BY 'password';
CREATE DATABASE wordpress;
CREATE USER IF NOT EXISTS ':1_SQL_USER'@'%' IDENTIFIED BY ':2_SQL_PASSWORD';
GRANT ALL PRIVILEGES ON wordpress.* TO ':1_SQL_USER'@'%';
FLUSH PRIVILEGES;

-- set password for root
ALTER USER 'root'@'localhost' IDENTIFIED BY ':3_SQL_ROOT_PASSWORD';
FLUSH PRIVILEGES;


GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY ':3_SQL_ROOT_PASSWORD';
FLUSH PRIVILEGES;
